import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans, Roboto_Condensed, Antonio, Macondo, Libre_Baskerville } from "next/font/google";
import "./globals.css";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
});

const macondo = Macondo({
  variable: "--font-macondo",
  subsets: ["latin"],
  weight: "400",
});

// ✅ Libre Baskerville
const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata = {
//   metadataBase: new URL("https://julio-herrera-blog.vercel.app"),

//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export const metadata = {
  metadataBase: new URL("https://julio-herrera-blog.vercel.app"),

  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${notoSans.variable}
          ${robotoCondensed.variable}
          ${antonio.variable}
          ${macondo.variable}
           ${libreBaskerville.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}




// import { Geist, Geist_Mono } from "next/font/google";
// import { Noto_Sans, Roboto_Condensed, Antonio, Macondo } from "next/font/google"; // Import Macondo font
// import "./globals.css";

// // Define fonts
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const notoSans = Noto_Sans({
//   variable: "--font-noto-sans",
//   subsets: ["latin"],
// });

// const robotoCondensed = Roboto_Condensed({
//   variable: "--font-roboto-condensed",
//   subsets: ["latin"],
// });

// const antonio = Antonio({
//   variable: "--font-antonio", 
//   subsets: ["latin"],
// });

// // Specify the correct weight for Macondo
// const macondo = Macondo({
//   variable: "--font-macondo", 
//   subsets: ["latin"],
//   weight: "400", // Specify weight here
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head></head>
//       <body className={`${geistSans.variable} ${geistMono.variable} ${notoSans.variable} ${robotoCondensed.variable} ${antonio.variable} ${macondo.variable} antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }
